[tool.poetry]
name = "coc-pydocstring"
version = "0.1.0"
description = ""
authors = ["yaegassy <yosstools@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
doq = "0.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
